#
Adaq: Makefile Adaq.c Adaq.h du.c t3.c eb.h eb.c gui.c ui.c \
      ad_shm.c ad_shm.h filterCoeffs.c
	gcc Adaq.c du.c t3.c eb.c gui.c ui.c ad_shm.c filterCoeffs.c \
         -I. -I../dudaq/files -lm -o Adaq
#
